name: workflow
on: [push, pull_request]
permissions:
  contents: read

jobs:
  job:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Prepare
        run: npm ci
      - name: Build
        run: npm run build
