name: workflow
on: [push, pull_request]
permissions:
  contents: read

jobs:
  job:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Prepare
        run: npm ci
      - name: Build
        run: npm run build
